/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import SubHeading from '@/components/shared/Text/SubHeading/SubHeading';
import { Content } from 'antd/es/layout/layout';
import NavBar from '@/components/NavBar/NavBar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Mochiy+Pop+One:wght@400&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <div className="h-full w-full top-0 left-0 -z-10 fixed">
          <div className="absolute inset-0 -z-10 h-full w-full items-center [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)]" />
        </div>
        <div className="relative mx-auto h-screen w-full text-white Mochiy_Pop_One">
          <header className="flex items-center w-full h-[40px] bg-transparent py-2">
            <NavBar />
          </header>
          <div className="flexCenter w-full h-[calc(100vh-60px)] flex-wrap">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
{
  /*h-[calc(100vh-60px)]

 <div className="absolute inset-0 -z-10 h-full w-full text-white items-center [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)]"> */
}
{
  /* </div> */
}
