/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import SubHeading from '@/components/SubHeading/SubHeading';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Mochiy+Pop+One:wght@400&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <div className="absolute inset-0 -z-10 h-full w-full text-white items-center [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)]">
          <header className="flex flex-row justify-between px-4 py-4 w-full h-[60px] bg-transparent">
            <div>
              <SubHeading text="Afaq Khan" bold={true} special={true} />
            </div>
            <div className="flex flex-row gap-x-4 text-[20px]">
              <span>
                <SubHeading text="Header" />
              </span>
              <span>
                <SubHeading text="Services" />
              </span>
              <span>
                <SubHeading text="Projects" />
                <h1></h1>
              </span>
              <span>
                <SubHeading text="About Me" />
              </span>
              <span>
                <SubHeading text="Footer" />
              </span>
            </div>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
